POST http://localhost:8080/events-register/group
Content-Type: application/json

{

  "userGroup": [
    {
      "email": "davidapsc@gmail.com", "mobile": "86616057"
    },
    {
      "email": "ryan.yap@gmail.com", "mobile": "97873327"
    }
  ], 
  "groupLeaderEmail": "davidapsc@gmail.com",
  "eventId": "GLOW1"
    
}

###

GET http://localhost:8080/events-register/GLOW1/reg-statuses/402f2448-8eb7-4a98-bb07-2c6b03f4e846
Content-Type: application/json
