POST http://localhost:8080/events-register/group
Content-Type: application/json

{

  "userGroup": [
    {
      "email": "davidapsc@gmail.com", "mobile": "06586616057"
    },
    {
      "email": "ryan.yap@gmail.com", "mobile": "06597873327"
    }
  ], 
  "groupLeaderEmail": "davidapsc@gmail.com",
  "eventId": "pink-sc-2024"

}

###

GET http://localhost:8080/events-register/GLOW1/reg-statuses/b8d33c7a-738d-48d4-8b36-deab0606a3b7
Content-Type: application/json

###

GET http://localhost:8080/events/
Content-Type: application/json

###

GET http://localhost:8080/events/pink-sc-2024
Content-Type: application/json